"""move_fields_to_units_and_rekey_department_data

Revision ID: b9997215396a
Revises: ad311e378314
Create Date: 2025-10-18 12:20:17.976997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b9997215396a'
down_revision: Union[str, Sequence[str], None] = 'ad311e378314'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('microbiology_data', sa.Column('unit_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('microbiology_data_sample_id_key'), 'microbiology_data', type_='unique')
    op.create_unique_constraint(None, 'microbiology_data', ['unit_id'])
    op.drop_constraint(op.f('microbiology_data_sample_id_fkey'), 'microbiology_data', type_='foreignkey')
    op.create_foreign_key(None, 'microbiology_data', 'units', ['unit_id'], ['id'])
    op.drop_column('microbiology_data', 'sample_id')
    op.add_column('pcr_data', sa.Column('unit_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('pcr_data_sample_id_key'), 'pcr_data', type_='unique')
    op.create_unique_constraint(None, 'pcr_data', ['unit_id'])
    op.drop_constraint(op.f('pcr_data_sample_id_fkey'), 'pcr_data', type_='foreignkey')
    op.create_foreign_key(None, 'pcr_data', 'units', ['unit_id'], ['id'])
    op.drop_column('pcr_data', 'sample_id')
    op.alter_column('samples', 'date_received',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('samples', 'company',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('samples', 'farm',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('samples', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('samples', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_column('samples', 'samples_number')
    op.drop_column('samples', 'sample_type')
    op.drop_column('samples', 'house')
    op.drop_column('samples', 'source')
    op.drop_column('samples', 'age')
    op.drop_column('samples', 'notes')
    op.add_column('serology_data', sa.Column('unit_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('serology_data_sample_id_key'), 'serology_data', type_='unique')
    op.create_unique_constraint(None, 'serology_data', ['unit_id'])
    op.drop_constraint(op.f('serology_data_sample_id_fkey'), 'serology_data', type_='foreignkey')
    op.create_foreign_key(None, 'serology_data', 'units', ['unit_id'], ['id'])
    op.drop_column('serology_data', 'sample_id')
    op.add_column('units', sa.Column('house', sa.String(), nullable=True))
    op.add_column('units', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('units', sa.Column('source', sa.String(), nullable=True))
    op.add_column('units', sa.Column('sample_type', sa.String(), nullable=True))
    op.add_column('units', sa.Column('samples_number', sa.Integer(), nullable=True))
    op.add_column('units', sa.Column('notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('units', 'notes')
    op.drop_column('units', 'samples_number')
    op.drop_column('units', 'sample_type')
    op.drop_column('units', 'source')
    op.drop_column('units', 'age')
    op.drop_column('units', 'house')
    op.add_column('serology_data', sa.Column('sample_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'serology_data', type_='foreignkey')
    op.create_foreign_key(op.f('serology_data_sample_id_fkey'), 'serology_data', 'samples', ['sample_id'], ['id'])
    op.drop_constraint(None, 'serology_data', type_='unique')
    op.create_unique_constraint(op.f('serology_data_sample_id_key'), 'serology_data', ['sample_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('serology_data', 'unit_id')
    op.add_column('samples', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('samples', sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('samples', sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('samples', sa.Column('house', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('samples', sa.Column('sample_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('samples', sa.Column('samples_number', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True))
    op.alter_column('samples', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('samples', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('samples', 'farm',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('samples', 'company',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('samples', 'date_received',
               existing_type=sa.DATE(),
               nullable=True)
    op.add_column('pcr_data', sa.Column('sample_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'pcr_data', type_='foreignkey')
    op.create_foreign_key(op.f('pcr_data_sample_id_fkey'), 'pcr_data', 'samples', ['sample_id'], ['id'])
    op.drop_constraint(None, 'pcr_data', type_='unique')
    op.create_unique_constraint(op.f('pcr_data_sample_id_key'), 'pcr_data', ['sample_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('pcr_data', 'unit_id')
    op.add_column('microbiology_data', sa.Column('sample_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'microbiology_data', type_='foreignkey')
    op.create_foreign_key(op.f('microbiology_data_sample_id_fkey'), 'microbiology_data', 'samples', ['sample_id'], ['id'])
    op.drop_constraint(None, 'microbiology_data', type_='unique')
    op.create_unique_constraint(op.f('microbiology_data_sample_id_key'), 'microbiology_data', ['sample_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('microbiology_data', 'unit_id')
    # ### end Alembic commands ###
